### PR TITLE
Fix typo preventing else condition from executing

### PR DESCRIPTION
**Pull request by brad-accuvant**

### CODE REVIEW

**Comment by kevthehermit** [comment]
Thanks for spotting that :)

**Comment by brad-accuvant** [comment]
No problem, BTW feel free to grab anything useful from https://github.com/brad-accuvant/cuckoo-modified/commit/6fe426f7b029844f3c5cddb4f39af561ffb5997a for NanoCore

-Brad

**Comment by kevthehermit** [comment]
Awesome Beats my hacky regex :). Will see if i can find some time to port the remainder over to your cuckoo fork

**Comment by brad-accuvant** [comment]
https://github.com/brad-accuvant/cuckoo-modified/commit/93b7d7f9d5b96fcdfe70f0d7a3b8de3d181d3a57 That should make the date/time correct wrt differing timezones as well

**Pull request merged**
